# Generated by Django 4.0.2 on 2022-10-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_car_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['manufacturer__name']},
        ),
    ]
